version: 2.1
orbs:
  pulumi: pulumi/pulumi@1.0.0
jobs:
  build:
    docker:
      - image: circleci/node:7.10
      - image: localstack/localstack:0.8.8
    working_directory: ~/repo
    steps:
      - checkout
      - pulumi/login
      - setup_remote_docker
      - run:
          command: |
            make all

      - pulumi/update:
          stack: '${APP_NAME}-${STAGE}'